### ISSUE TITLE
Can’t preview and post images

### ISSUE THREAD

**Issue by Letterus** [luki-ev/synod-ios#2]
### Steps to reproduce

1. Where are you starting? What can you see?
2. What do you click?
3. More steps…

#### What happened instead?

Can‘t view and post images.

![IMG_2489](https://github.com/luki-ev/synod-ios/assets/2911501/9fd6f166-7561-4f2d-a053-05acb2fe1678)
![IMG_2490](https://github.com/luki-ev/synod-ios/assets/2911501/da2017e0-2154-4350-a69a-2230e1c4923c)
![IMG_2491](https://github.com/luki-ev/synod-ios/assets/2911501/ff33fad4-ce62-4b4c-b61e-a7107bdc399b)

Checked Wifi and LTE.

### Your phone model

iPhone SE 2020

### Operating system version

16.5.1

### Application version

1.10.11

### Homeserver

synod.im

### Will you send logs?

No

**Comment by csett86** [comment]
This is related to https://github.com/matrix-org/synapse/issues/15873, fixed via manual patch that will come with the next version of synapse: https://github.com/matrix-org/synapse/pull/15876
